name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: '3.11'
      - name: Create sdist
        run: |
          python -m pip install --upgrade pip setuptools
          python setup.py sdist
        shell: bash
      - name: List output directory
        run: ls -lh dist/dm_tree*.tar.gz
        shell: bash
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-sdist
          path: dist/dm_tree*.tar.gz

  bdist-wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-2022]  # latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: true
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
        with:
          python-version: "3.11"
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a  # v3.3.0
        with:
          platforms: all
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: universal2
          CIBW_BUILD: "cp310-* cp311-* cp312-* cp313-* cp313t-*"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_FREE_THREADED_SUPPORT: True
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_SKIP: "*musllinux* *i686* *win32* *t-win*"
          CIBW_TEST_COMMAND: pytest --pyargs tree
          CIBW_TEST_REQUIRES: pytest
          MAKEFLAGS: "-j$(nproc)"
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-bdist-wheel-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*.whl
