name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Create sdist
        run: |
          python -m pip install --upgrade pip setuptools
          python setup.py sdist
        shell: bash
      - name: Directory listing
        run: ls -lh dist/dm_tree*.tar.gz
        shell: bash
      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-${{ github.workflow }}-${{ github.run_number }}
          path: dist/dm_tree*.tar.gz

  wheel-x86_64:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]
        python_tag: [cp310, cp311, cp312, cp313]
        include:
          - os: windows-latest
            os_tag: win_amd64
          - os: ubuntu-latest
            os_tag: manylinux_x86_64
          - os: macos-13
            os_tag: macos_x86_64

    name: "wheel: ${{ matrix.python_tag }}-${{ matrix.os_tag }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install prerequisites
        run: |
          set -xe
          pwd
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cibuildwheel
        shell: bash

      - name: Build and test
        run: set -xe && python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python_tag }}-${{ matrix.os_tag }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64
          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST: pip install -r requirements-test.txt
          CIBW_TEST_COMMAND: pytest --pyargs tree
        shell: bash

      - name: Directory listing
        run: ls -lh wheelhouse/dm_tree*.whl
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-${{ github.workflow }}-${{ github.run_number }}
          path: wheelhouse/dm_tree*.whl

  wheel-apple_silicon:
    strategy:
      matrix:
        python_tag: [cp310, cp311, cp312, cp313]
        macos_arch: [arm64, universal2]

    name: "wheel: ${{ matrix.python_tag }}-macos_${{ matrix.macos_arch }}"
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install prerequisites
        run: |
          set -xe
          pwd
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cibuildwheel
        shell: bash

      - name: Build and test
        run: set -xe && python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python_tag }}-macos_${{ matrix.macos_arch }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_ARCHS_MACOS: ${{ matrix.macos_arch }}
          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST: pip install -r requirements-test.txt
          CIBW_TEST_COMMAND: "if [ \"${CIBW_ARCHS_MACOS}\" = \"universal2\" ]; then pytest --pyargs tree; fi"
        shell: bash

      - name: Directory listing
        run: ls -lh wheelhouse/dm_tree*.whl
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-${{ github.workflow }}-${{ github.run_number }}
          path: wheelhouse/dm_tree*.whl

  wheel-aarch:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_tag: [cp310, cp311, cp312, cp313]
        arch: [aarch64, ppc64le, s390x, i686]
        include:
          - arch: aarch64
            arch_tag: manylinux_aarch64
          - arch: ppc64le
            arch_tag: manylinux_ppc64le
          - arch: s390x
            arch_tag: manylinux_s390x
          - arch: i686
            arch_tag: manylinux_i686

    if: false
    name: "wheel: ${{ matrix.python_tag }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Install prerequisites
        run: |
          set -xe
          pwd
          python --version
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install cibuildwheel
        shell: bash

      - name: Build and test
        run: set -xe && python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python_tag }}-${{ matrix.arch_tag }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_REQUIRES: pytest
          CIBW_BEFORE_TEST: pip install -r requirements-test.txt
          CIBW_TEST_COMMAND: pytest --pyargs tree
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        shell: bash

      - name: Directory listing
        run: ls -lh wheelhouse/dm_tree*.whl
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'created') }}
        with:
          name: dm-tree-${{ github.workflow }}-${{ github.run_number }}
          path: wheelhouse/dm_tree*.whl
